name: Feature Request
description: File a feature request
title: "[Feature]: "
labels: ["type:feature", triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe the Feature"
      description: "Please include expected behavior, as well as usage cases."
